HUB_DOMAIN: "virtualplaces-uva.eu"
ADM_EMAIL: "t.j.r.lanjouw@uva.nl"
Namespace: "hcce"
Container_Dockerhub_Username: "mozillareality"
Container_Tag: "stable-latest"
DB_USER: "postgres"
DB_PASS: "123456"
DB_NAME: "retdb"
DB_HOST: "pgbouncer"
DB_HOST_T: "pgbouncer-t"
PGRST_DB_URI: "postgres://$DB_USER:$DB_PASS@pgbouncer/$DB_NAME"
PSQL: "postgres://$DB_USER:$DB_PASS@pgbouncer/$DB_NAME"
SMTP_SERVER: "smtp.tem.scaleway.com"
SMTP_PORT: "2587"
SMTP_USER: "f2cb59e0-1955-4ed4-a969-6cff4fe5f5bc"
SMTP_PASS: "9cd67d01-c7ff-4d26-ab86-7be433c7f9a5"
NODE_COOKIE: "wxtYwB3KqC6a8wdEKdGsvuDT4v8xNwsc"
GUARDIAN_KEY: "8rwXblAwDnRF48KXvR561fHXBXdVG4vD"
PHX_KEY: "nMvIWCRM0lnNhnvwz6ecVHD3JXQWSdCT"
SKETCHFAB_API_KEY: "2ca0d87f6e524da18d25c0c7dc9c5310"
TENOR_API_KEY: "?"
GENERATE_PERSISTENT_VOLUMES: "Yes"
PERSISTENT_VOLUME_SIZE: "10Gi"
OVERRIDE_RETICULUM_IMAGE: "hubsfoundation/ret:$Container_Tag"
OVERRIDE_POSTGREST_IMAGE: "No"
OVERRIDE_POSTGRES_IMAGE: "No"
OVERRIDE_PGBOUNCER_IMAGE: "No"
OVERRIDE_HUBS_IMAGE: "hubsfoundation/hubs:$Container_Tag"
OVERRIDE_SPOKE_IMAGE: "hubsfoundation/spoke:$Container_Tag"
OVERRIDE_NEARSPARK_IMAGE: "No"
OVERRIDE_PHOTOMNEMONIC_IMAGE: "No"
OVERRIDE_DIALOG_IMAGE: "No"
OVERRIDE_COTURN_IMAGE: "No"
OVERRIDE_HAPROXY_IMAGE: "No"
